### ISSUE TITLE
Checklist for voter

### ISSUE THREAD

**Issue by ceremcem** [ceremcem/vote-is-well#7]
Print a piece of paper that contains a checklist for voter: 

- [ ] does ballot have foo property
- [ ] does ballot have bar property
- [ ] Is there only one ballot (duplicate ballots in an envelope is considered void)
- [ ] does envelope have baz property 

Checklist should be printed out since no smartphones are allowed while voting process.
